#sol_1
set.seed(123)
N = function(n)
{
  return(runif(n))
}
N(1000)

#sol_2
set.seed(123)
histogram = function(n)
{
  return(hist(runif(n), main = "hist of generated sample"))
}
histogram(1000)

#sol_3
set.seed(123)
K = function(k)
{
  return(seq(0,1,length.out = k+1))
}
K(10)
#sol_4
set.seed(123)
chi_sq = function(N,K)
{
  x = runif(N)
  y = seq(0,1, length.out = K+1)
  O = hist(x, breaks = y, plot = FALSE)$counts
  E = rep(N/K,K)
  return(sum(((O - E)^2)/E))
}
chi_sq(1000,10)
#sol_5
chi_sq(50,5)
chi_sq(100,5)
chi_sq(200,5)
chi_sq(1000,5)
chi_sq(50,10)
chi_sq(100,10)
chi_sq(200,10)
chi_sq(1000,10)
chi_sq(50,15)
chi_sq(100,15)
chi_sq(200,15)
chi_sq(1000,15)
par(mfrow=c(2,2))
hist(runif(50), main = "hist generated by sample of size 50")
hist(runif(100), main = "hist generated by sample of size 50")
hist(runif(200), main = "hist generated by sample of size 50")
hist(runif(1000), main = "hist generated by sample of size 50")
par(mfrow = c(1,1))
#sol_6
set.seed(123)
my_table = function(N,K)
{
  results = data.frame(N = integer(), K = integer(), chi_sq = numeric())
  for (i in N)
  {
    for (j in K)
    {
      O = i/j
      k = seq(0,1, length.out = j+1)
      E = hist(runif(i), plot = F, breaks = k)$counts
      chi_sq = sum(((O - E)^2)/E)
      results = rbind(results, data.frame(N = i, K = j, chi_sq = chi_sq))
    }
  }
  return(results)
}
N = list(50,100,200,1000)
K = list(5,10,15)
my_table(N,K)
